### PR TITLE
feature/matched proteins table

### PR DESCRIPTION
**Pull request by pverscha**
This PR introduces the new MatchedProteinsTable, that's a port from the proteins table in the single peptide analysis app in the Unipept web app. 

The table has been expanded with filterable and sortable columns. All data visible in the columns (as well as the functional annotations that appear when a row is expanded can be filtered). This filtering is implemented in a naive way at this point in time, which might need further optimisation in the future if it proofs not to be performant enough for large lists of proteins.

By clicking on the column headers, the table with respect to the values in the selected column.

Screenshots:
_Table:_
localhost_5000_search_single (2)

_Expandable rows with functional annotations information:_
image

_Filtering:_
image

_Error handling in case no associated peptide data was found:_
image

Closes issue #114

### CODE REVIEW

**Comment by bmesuere** [comment]
This looks very good. 

- Maybe we can think of a way to somehow indicate if/how many annotations there are for a certain row? If there are zero, the expand arrow can be omitted. Ideas "x functional annotations", "x go terms, x ec numbers", an ec/go/interpro icon of it has any of those annotations, or simply a "badge" to show the number of functional annotations
- the button is a bit prominent now for the limited value it has. In fact, I don't know if any other option than "UniProt" is used. Maybe we can just link to that and get rid of the button altogether?

**Comment by pverscha** [comment]
@bmesuere I've slightly updated the component. I've added icons that indicate the presence of the different types of functional annotations. I've been experimenting with badges, but that did not result in a satisfiable result. I chose to display the amount of annotations in a tooltip instead.

_Icons_:
image

_Tooltips_:
image

The expand-button is now disabled when no annotations are present. Would you rather have it disappear in that case?

I also made the UniProt-button less prominent. There are 3 different external sources to which this button points, so we can't replace it by a link.

image

**Comment by bmesuere** [comment]
I like the icons! Would it make sense to display a desaturated/dimmed version of the icon if no annotations of that type are present instead of showing nothing? I think that would improve the visual rhythm of the table (but might not look good).

Does the tooltip component allow to use styles inside of it? It might be useful to put the "x go terms" part (or only the number) in bold.

Disabling the expand is ok. Maybe add a tooltip saying why it's disabled?

I know that there are 3 external sources, but I think both pride and peptideatlas are never used and (at least for pride) never return a useful result anyway so we could maybe remove them.

**Comment by pverscha** [comment]
@bmesuere I've been experimenting with the different options of showing the icons. I think the washed-out variant is the best-looking one:

image

I've also removed the dropdown and replaced it by one icon that leads to the external information source.

**Comment by bmesuere** [comment]
Very clean!

**Pull request merged**
